name: Run Python Scripts

on:
  schedule:
    # Run the workflow every day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows the workflow to be manually triggered

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run site.py
      run: |
        python site.py

    - name: Run more.py
      run: |
        python more.py

    - name: Run csv_to_mongo.py
      env:
        MONGO_URL: ${{ secrets.MONGO_URL }}  # Ensure you add your MongoDB URL as a secret in your repository settings
      run: |
        python csv_to_mongo.py
